apiVersion: v1
kind: Service              
metadata:
  name: consumer
spec:
  type: NodePort      
  ports:
  - port: 80              
    targetPort: 8080   
    nodePort: 32100      
  selector:            
    app: consumer    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 2                                          
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  selector:
    matchLabels:
      app: consumer
      tier: rabbit-go
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: consumer
        tier: rabbit-go
    spec:
      containers:
      - image: alessandroargentieri/rabbit-go-consumer
        name: consumer
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-credentials
              key: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit-credentials
              key: password
        - name: RABBITMQ_URL
          value: "rabbit:5672"  # "amqp://myuser:password@localhost:5672/"
        - name: PORT
          value: "8080"  
        ports:
        - containerPort: 8080
          name: consumer-api
